### PR TITLE
Add fix for failing valueInteger

### LINKED ISSUE #324: Fix failing valueInteger when generating QuestionnaireResponse
This error is encountered when run vallidation of questionnaires with integers
` HAPI-1821: [element="valueInteger"] Invalid attribute value "69.44130983223977": java.lang.NumberFormatException: For input string: "69.44130983223977"`

### PR DESCRIPTION
**Pull request by sharon2719**
**IMPORTANT: Where possible all PRs must be linked to a Github issue**

Fixes #324 
**Engineer Checklist**
- [x] I have run `./gradlew spotlessApply` to check my code follows the project's style guide
- [x] I have built using the command `./gradlew clean assemble` and run the efsity jar to verify my change fixes the issue and does not break the application

### CODE REVIEW

**Review by pld — APPROVED** [review]

File: efsity-cli/src/test/java/org/smartregister/command/QuestionnaireResponseGeneratorCommandTest.java [hunk 1]
```diff
@@ -162,4 +162,141 @@ void testGenerateReferenceValue() {
...
+  void testGenerateIntegerAnswer() {
+    JSONObject extras = new JSONObject();
+    JSONArray questions = new JSONArray();
+
+    JSONObject answer =
+        QuestionnaireResponseGeneratorCommand.generateAnswer(
+            "integer", questions, "linkId", extras);
+
+    assertNotNull(answer);
+    assertTrue(answer.has("valueInteger"));
```
Comment (dubdabasoduba) [inline efsity-cli/src/test/java/org/smartregister/command/QuestionnaireResponseGeneratorCommandTest.java:189]: Please check if the answer is of type

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]
